version: "3"
volumes: 
  db-data:
services:
  backend1:
    build: .
    container_name: cashflow-backend1
    depends_on:
      - mysql
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - MYSQL_HOST=mysql
      - MYSQL_USER=app
      - MYSQL_PASSWORD=123   
    command: ["/home/wait-for-it.sh", "mysql:3306", "--", "java" ,"-jar", "/home/cash-flow.jar"]
  backend2:
    container_name: cashflow-backend2
    depends_on:
      - backend1
    build: .
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - MYSQL_HOST=mysql
      - MYSQL_USER=app
      - MYSQL_PASSWORD=123  
  backend3:
    container_name: cashflow-backend3
    depends_on:
      - backend1
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - MYSQL_HOST=mysql
      - MYSQL_USER=app
      - MYSQL_PASSWORD=123        
  mysql:
    env_file: ./docker.env
    container_name: cashflow-mysql
    image: mariadb
    volumes:
      - db-data:/var/lib/mysql/data:rw
  nginx:
    image: nginx:latest
    depends_on: 
      - backend1
      - backend2
      - backend3
    volumes: 
      - ./nginx.conf.template:/etc/nginx/conf.d/nginx.conf.template
    ports:
      - "80:80"
    container_name: cashflow-nginx
    environment: 
      - BACKEND_1=backend1
      - BACKEND_2=backend2
      - BACKEND_3=backend3
    command: /bin/bash -c "envsubst '$$BACKEND_1 $$BACKEND_2 $$BACKEND_3' < /etc/nginx/conf.d/nginx.conf.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"


